name: avataar_generator
description: A simple svg generator that gives awesome emojis. This package can be used anywhere with Dart like Angular dart, Flutter etc.
version: 1.1.1
author: Kushagra Saxena <saxena.kushagra3107@gmail.com>
homepage: https://devslane.com
repository: https://github.com/devslane/Avataar-Generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
